### PR TITLE
Update to latest SHA256 hash

### PR DESCRIPTION
**Pull request by RisingFog**
Fixes the install error with the mismatching SHA256 hash.

### CODE REVIEW

**Comment by Kethsar** [comment]
I think this should have the URL updated to use `https://github.com/Kethsar/ytarchive/archive/refs/tags/v0.3.2.tar.gz` and its associated hash as well, now that there's a properly tagged release, and will be going forward (whenever I work on it, which is never).
That should resolve these hash mismatches indefinitely, and only need updates to add new releases there after.

**Comment by omerien** [comment]
> I think this should have the URL updated to use `https://github.com/Kethsar/ytarchive/archive/refs/tags/v0.3.2.tar.gz` and its associated hash as well, now that there's a properly tagged release, and will be going forward (whenever I work on it, which is never). That should resolve these hash mismatches indefinitely, and only need updates to add new releases there after.

Now done in #5

**Comment by danirukun** [comment]
@RisingFog I might close this in favor of the newer #5 if that's okay with you.

**Comment by RisingFog** [comment]
> @RisingFog I might close this in favor of the newer #5 if that's okay with you.

Yeah that’s fine with me

**Pull request closed without merging**
